modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = "https://github.com/Minenash/Seamless-Loading-Screen/issues"
license = "MIT"

[[mods]]
modId = "seamless_loading_screen"
version = "${version}"
displayName = "Seamless Loading Screen"
authors = "Minenash"
description = '''
Takes a screenshot of the game when you leave a world or server, and displays it when you rejoin it
'''
logoFile = "icon.png"

[mods."sodium:options"]
"mixin.features.gui.fast_loading_screen" = false

[[dependencies.seamless_loading_screen]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless_loading_screen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"